service: funko-pop-addiction-enabler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getChaliceCollectiblesProducts:
    handler: chaliceCollectibles/handler.getChaliceCollectiblesProducts
    events:
      - http:
          path: challice/products
          method: get
          cors: true
          
plugins:
  - serverless-finch

custom:
  client:
    bucketName: funko-pop-addiction-enabler-bucket
    distributionFolder: client/build
    errorDocument: index.html