service: funko-pop-addiction-enabler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getChaliceCollectiblesProducts:
    handler: chaliceCollectibles/handler.getChaliceCollectiblesProducts
    events:
      - http:
          path: challice/products
          method: get
          cors: true
